# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 22 17:23:19 2020
# ------------------------------------------------

package:
    name: pylint
    version: 2.6.0
source:
    sha256: bb4a908c9dadbc3aac18860550e870f58e1a02c9f2c204fdf5693d73be061210
    url: https://pypi.io/packages/source/p/pylint/pylint-2.6.0.tar.gz
build:
    entry_points:
        - epylint = pylint:run_epylint
        - pylint = pylint:run_pylint
        - pyreverse = pylint:run_pyreverse
        - symilar = pylint:run_symilar
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/pylint_1598117058668/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37hc8dfbb8_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - attrs 20.1.0 pyh9f0ad1d_0
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37hc8dfbb8_0
        - importlib-metadata 1.7.0 py37hc8dfbb8_0
        - importlib_metadata 1.7.0 0
        - iniconfig 1.0.1 pyh9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
        - libstdcxx-ng 9.3.0 hdf63c60_15
        - more-itertools 8.4.0 py_0
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - packaging 20.4 pyh9f0ad1d_0
        - pip 20.2.2 py_0
        - pluggy 0.13.1 py37hc8dfbb8_2
        - py 1.9.0 pyh9f0ad1d_0
        - pyparsing 2.4.7 pyh9f0ad1d_0
        - pytest 6.0.1 py37hc8dfbb8_0
        - pytest-runner 5.2 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37hc8dfbb8_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - toml 0.10.1 pyh9f0ad1d_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h516909a_1007
    run:
        - astroid >=2.4.0,<=2.5
        - isort >=4.2.5,<6
        - mccabe >=0.6,<0.7
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - toml >=0.7.1
test:
    commands:
        - pylint --help
        - type epylint
        - pyreverse --help
        - symilar --help
    imports:
        - pylint
        - pylint.checkers
        - pylint.extensions
        - pylint.pyreverse
        - pylint.reporters
        - pylint.reporters.ureports
about:
    description: 'Pylint is a tool that checks for errors in Python code, tries to
        enforce a

        coding standard and looks for code smells.

        '
    dev_url: https://github.com/PyCQA/pylint/
    doc_source_url: https://github.com/PyCQA/pylint/blob/master/doc/index.rst
    doc_url: https://pylint.readthedocs.io/en/latest/
    home: http://www.pylint.org/
    license: GPL-2.0-only
    license_file: COPYING
    summary: python code static checker
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - jakirkham
        - jjhelmus
        - timleslie
