# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jul  8 18:40:47 2018
# ------------------------------------------------

package:
    name: mccabe
    version: 0.6.1
source:
    sha256: dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f
    url: https://pypi.io/packages/source/m/mccabe/mccabe-0.6.1.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - atomicwrites 1.1.5 py27_0
        - attrs 18.1.0 py_1
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py27_0
        - funcsigs 1.0.2 py_2
        - libgcc-ng 7.2.0 hdf63c60_3
        - more-itertools 4.2.0 py_0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - pip 9.0.3 py27_0
        - pluggy 0.6.0 py_0
        - py 1.5.4 py_0
        - pytest 3.6.2 py27_0
        - pytest-runner 4.2 py_0
        - python 2.7.15 0
        - readline 7.0 0
        - setuptools 39.2.0 py27_0
        - six 1.11.0 py27_1
        - sqlite 3.20.1 2
        - tk 8.6.7 0
        - wheel 0.31.1 py27_0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - mccabe
about:
    dev_url: https://github.com/PyCQA/mccabe
    home: https://github.com/PyCQA/mccabe
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: McCabe complexity checker for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - jakirkham
        - ocefpaf
        - sigmavirus24
