# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 15 04:41:13 2020
# ------------------------------------------------

package:
    name: isort
    version: 5.4.2
source:
    sha256: d488ba1c5a2db721669cc180180d5acf84ebdc5af7827f7aaeaa75f73cf0e2b8
    url: https://pypi.io/packages/source/i/isort/isort-5.4.2.tar.gz
build:
    entry_points:
        - isort = isort.main:main
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/isort_1597466533836/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: py37hc8dfbb8_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - attrs 19.3.0 py_0
        - brotlipy 0.7.0 py37h8f50634_1000
        - ca-certificates 2020.6.20 hecda079_0
        - cachecontrol 0.12.6 py_0
        - cachy 0.3.0 py_0
        - certifi 2020.6.20 py37hc8dfbb8_0
        - cffi 1.14.1 py37h2b28604_0
        - chardet 3.0.4 py37hc8dfbb8_1006
        - cleo 0.7.6 py_0
        - clikit 0.4.3 pyh9f0ad1d_0
        - cryptography 3.0 py37hb09aad4_0
        - dbus 1.13.6 he372182_0
        - entrypoints 0.3 py37hc8dfbb8_1001
        - expat 2.2.9 he1b5a44_2
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.65.0 h6f030ca_0
        - html5lib 1.1 pyh9f0ad1d_0
        - idna 2.10 pyh9f0ad1d_0
        - importlib-metadata 1.1.3 py37hc8dfbb8_0
        - importlib_metadata 1.1.3 0
        - jeepney 0.4.3 py_0
        - jsonschema 3.2.0 py37hc8dfbb8_1
        - keyring 18.0.1 py37hc8dfbb8_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - libiconv 1.15 h516909a_1006
        - libstdcxx-ng 9.3.0 hdf63c60_14
        - lockfile 0.12.2 py_1
        - msgpack-python 1.0.0 py37h99015e2_1
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pastel 0.2.0 py_0
        - pcre 8.44 he1b5a44_0
        - pexpect 4.8.0 py37hc8dfbb8_1
        - pip 20.2.2 py_0
        - pkginfo 1.5.0.1 py_0
        - poetry 1.0.9 py37hc8dfbb8_0
        - ptyprocess 0.6.0 py_1001
        - pycparser 2.20 pyh9f0ad1d_2
        - pylev 1.3.0 py_0
        - pyopenssl 19.1.0 py_1
        - pyparsing 2.4.7 pyh9f0ad1d_0
        - pyrsistent 0.14.11 py37h8f50634_1
        - pysocks 1.7.1 py37hc8dfbb8_1
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - requests 2.24.0 pyh9f0ad1d_0
        - requests-toolbelt 0.8.0 py_1
        - secretstorage 3.1.2 py37hc8dfbb8_1
        - setuptools 49.6.0 py37hc8dfbb8_0
        - shellingham 1.3.2 py_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.32.3 h4cf870e_1
        - tk 8.6.10 hed695b0_0
        - tomlkit 0.5.11 py37hc8dfbb8_1
        - urllib3 1.25.10 py_0
        - webencodings 0.5.1 py_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h516909a_1007
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - setuptools
test:
    commands:
        - isort --help
    imports:
        - isort
about:
    description: 'isort is a Python utility / library to sort imports alphabetically,
        and

        automatically separated into sections. It provides a command line utility,

        Python library and plugins for various editors to quickly sort all your

        imports. It currently cleanly supports Python 2.6 - 3.5 using pies to

        achieve this without ugly hacks and/or py2to3.

        '
    dev_url: https://github.com/timothycrosley/isort
    doc_source_url: https://github.com/timothycrosley/isort/blob/develop/README.rst
    doc_url: http://isort.readthedocs.io/en/latest/
    home: https://github.com/timothycrosley/isort
    license: MIT
    license_file: LICENSE
    summary: A Python utility / library to sort Python imports.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - nehaljwani
        - nicoddemus
        - ocefpaf
