# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun  8 19:37:01 2020
# ------------------------------------------------

package:
    name: astroid
    version: 2.4.2
source:
    sha256: 2f4078c2a41bf377eea06d71c9d2ba4eb8f6b1af2135bec27bbbb7d8f12bb703
    url: https://pypi.io/packages/source/a/astroid/astroid-2.4.2.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/astroid_1591645081755/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py37hc8dfbb8_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - attrs 19.3.0 py_0
        - ca-certificates 2020.4.5.2 hecda079_0
        - certifi 2020.4.5.2 py37hc8dfbb8_0
        - importlib-metadata 1.6.1 py37hc8dfbb8_0
        - importlib_metadata 1.6.1 0
        - ld_impl_linux-64 2.34 h53a641e_5
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - more-itertools 8.3.0 py_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - packaging 20.4 pyh9f0ad1d_0
        - pip 20.1.1 py_1
        - pluggy 0.13.1 py37hc8dfbb8_1
        - py 1.8.1 py_0
        - pyparsing 2.4.7 pyh9f0ad1d_0
        - pytest 5.4.3 py37hc8dfbb8_0
        - pytest-runner 5.2 py_0
        - python 3.7.6 h8356626_5_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 47.1.1 py37hc8dfbb8_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wcwidth 0.2.4 pyh9f0ad1d_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zipp 3.1.0 py_0
        - zlib 1.2.11 h516909a_1006
    run:
        - lazy-object-proxy ==1.4.*
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - setuptools
        - six >=1.12,<2
        - typed-ast >=1.4.0,<1.5
        - wrapt ==1.11.*
test:
    commands:
        - python -m pip check
    imports:
        - astroid
        - astroid.modutils
    requires:
        - pip
about:
    description: 'Astroid provide a common base representation of python source code
        for

        projects such as pychecker, pyreverse, pylint.

        '
    dev_url: https://github.com/PyCQA/astroid
    doc_source_url: https://github.com/PyCQA/astroid/blob/master/doc/index.rst
    doc_url: http://astroid.readthedocs.io/en/latest/?badge=latest
    home: https://www.astroid.org/
    license: LGPL-2.1-only
    license_family: LGPL
    license_file: COPYING.LESSER
    summary: A abstract syntax tree for Python with inference support.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ericdill
        - jakirkham
        - jjhelmus
        - ocefpaf
