# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jan 13 19:25:29 2020
# ------------------------------------------------

package:
    name: typed-ast
    version: 1.4.1
source:
    sha256: 8c8aaad94455178e3187ab22c8b01a3837f8ee50e09cf31f1ba129eb293ec30b
    url: https://pypi.io/packages/source/t/typed_ast/typed_ast-1.4.1.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/typed-ast_1578943582909/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py37h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.33.1 he1b5a44_7
        - binutils_linux-64 2.33.1 h9595d00_16
        - gcc_impl_linux-64 7.3.0 hd420e75_4
        - gcc_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 19.3.1 py37_0
        - python 3.7.6 h357f687_2
        - readline 8.0 hf8c457e_0
        - setuptools 45.0.0 py37_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.3.0
        - python >=3.7,<3.8.0a0
test:
    imports:
        - typed_ast
about:
    description: 'typed_ast is a Python 3 package that provides a Python 2.7 and Python
        3

        parser similar to the standard ast library. Unlike ast, the parsers in

        typed_ast include PEP 484 type comments and are independent of the version

        of Python under which they are run. The typed_ast parsers produce the

        standard Python AST (plus type comments), and are both fast and correct, as

        they are based on the CPython 2.7 and 3.6 parsers.

        '
    dev_url: https://github.com/python/typed_ast
    doc_url: https://github.com/python/typed_ast/blob/master/README.md
    home: https://github.com/python/typed_ast
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: a fork of Python 2 and 3 ast modules with type comment support
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - ocefpaf
