# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Mar 23 00:00:55 2020
# ------------------------------------------------

package:
    name: lazy-object-proxy
    version: 1.4.3
source:
    sha256: f3900e8a5de27447acbf900b4750b0ddfd7ec1ea7fbaf11dfa911141bc522af0
    url: https://pypi.io/packages/source/l/lazy-object-proxy/lazy-object-proxy-1.4.3.tar.gz
build:
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/lazy-object-proxy_1584921710266/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py37h8f50634_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_0
        - binutils_linux-64 2.34 hc952b39_18
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_18
        - ld_impl_linux-64 2.34 h53a641e_0
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37hc8dfbb8_1
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - pip 20.0.2 py_2
        - python 3.7.6 h357f687_4_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.1 py37hc8dfbb8_0
        - setuptools-scm 3.5.0 py_1
        - setuptools_scm 3.5.0 1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h516909a_1002
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.3.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - lazy_object_proxy
        - lazy_object_proxy.cext
about:
    dev_url: https://github.com/ionelmc/python-lazy-object-proxy
    doc_source_url: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/docs/index.rst
    doc_url: https://python-lazy-object-proxy.readthedocs.org
    home: https://github.com/ionelmc/python-lazy-object-proxy
    license: BSD-2-Clause
    license_file: LICENSE
    summary: A fast and thorough lazy object proxy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - nehaljwani
        - ocefpaf
        - xylar
